language: python
sudo: required
dist: bionic
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8

matrix:
  include:
    - language: generic
      python: 2.7
      os: osx
    - language: generic
      python: 3.5
      os: osx
    - language: generic
      python: 3.6
      os: osx
    - language: generic
      python: 3.7
      os: osx
    - language: generic
      python: 3.8
      os: osx

before_install:
  - pip install --quiet codecov wheel

install:
  - make install

script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
